
name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x.x
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run vitest
        run: bun vitest --coverage
      - name: 'Report Coverage'
        uses:  davelosert/vitest-coverage-report-action@v2
